### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by IdioticMage** [MiningMark48/Pearcel-Mod#11]
the harvested compressed sugar cane in any slot of the crafting grid makes 9 sugar, it should also be able to be turned into the compressed sugar cane block but the recipes are the same so the sugar result is the only one that shows

**Comment by zetcipher** [comment]
All sugar cane stuff has been removed in the 1.7 pre-releases.

**Comment by MiningMark48** [comment]
The sugar cane stuff has been moved to Numbah90's Better Sugar Cane Mod.
