### ISSUE TITLE
Angel ring from Extra Utilities cannot fly if Parcel Mod is installed.

### ISSUE THREAD

**Issue by ircmaan** [MiningMark48/Pearcel-Mod#15]
On http://forum.feed-the-beast.com/threads/1-7-10-material-energy-4.57967/page-153
" I crafted an Angel ring from Extra Utilities , but it doesn't give me the ability to fly.
- It is a problem with the Pearcel Mod. Uninstalling will give the flight ability back to the user.
  it does unfortunately mean that the above solution null and voids a few quests."

Gem Armor from ProjectE cannot hover (stay fly in one point) - only slow fly_up with key "space" or fly_down

I have this problem too. I do not want uninstall good Pearcel Mod. Can you fix it?

Thanx anyway

**Comment by MiningMark48** [comment]
I will try to have this fixed in the next version (which will be soon due to newly discovered bugs). For now, there is an option in the Pearcel Mod config file that asks if you would like to disable the Pearcel Cloud, enabling this to true should fix your issue. 

http://i.imgur.com/7ZcsNYb.png

**Comment by ircmaan** [comment]
version 1.8.7 pearcelmod.cfg I have not "disable the Pearcel Cloud"

# Configuration file

general {
    # Should the Pearcel Staff be added to the game? [default: true]
    B:"Add Pearcel Staff?"=true

```
# Should the Pearcel Cloud make you hunger go down? [default: true]
B:"Add exhaustion to Pearcel Cloud?"=true

# What is the durability of the summoner's activation pearcel? [range: 1 ~ 100, default: 20]
I:"Durability for Summoner's Activation Pearcel"=20

# Add Special dice rolls? [default: true]
B:"Have special dice rolls?"=true

# Should ME^Matter recipes be added? [default: true]
B:"ME^Matter Recipes"=true

# What is the max height the Pearcel Staff will give you a boost? [range: 1 ~ 256, default: 150]
I:"Max height for Pearcel Staff boost"=150

# Maximum range for the Charged Pearcel Sword's Lightning [range: 1 ~ 100, default: 5]
I:"Max. Lightning Range"=5

# Minimum range for the Charged Pearcel Sword's Lightning [range: 0 ~ 99, default: 2]
I:"Min. Lightning Range"=2

# What is the range in which something may be summoned? [range: 1 ~ 25, default: 3]
I:"Range for Summoner"=3

# What is the frequency of torches that can be placed by the torcher block? [range: 50 ~ 2, default: 2]
I:"Torcher Frequency"=2

# What is the range of torches that can be placed by the torcher block? [range: 1 ~ 500, default: 25]
I:"Torcher Range"=25

# Should the particles of the Pearcel Cloud be added to the game? [default: true]
B:"Use Pearcel Cloud Particles?"=true
B:configValue=true
```

}

**Comment by ircmaan** [comment]
I dont know where I can download new Pearcel Mod. Or you mean alpha Pearcel Mod v2.0.0?

**Comment by MiningMark48** [comment]
Pearcel Mod v2.0.0 (alpha) is currently the latest version. A new version will be released soon containing major bug fixes.
