### ISSUE TITLE
[Client thread/ERROR] [FML]: A critical error occurred instantiating the gui factory for mod pearcelmod

### ISSUE THREAD

**Issue by GiovanniCardamone** [MiningMark48/Pearcel-Mod#17]
Hi,

im on Ubuntu/Linux and i have download a minecraft pack (AntiMaterialEnergy) that use yours mod.
But seems there is a mistake; because i cant run pack. 

this is the issue: http://paste.feed-the-beast.com/view/a5d75ef6

i got this Java Exception that stuck the launcher to launch the client.

`java.lang.ClassNotFoundException: com.miningmark48.pearcelmod.client.gui.GuiFactor
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)`

So, i search on git the mod, and only i can find in the package (https://github.com/MiningMark48/Pearcel-Mod/tree/master/src/main/java/com/miningmark48/pearcelmod/client/gui) GuiFactory instead of GuyFactor.

Seems you have put bad reference for the class, how i can fix?

**Comment by MiningMark48** [comment]
What version of the pack are you using and what Pearcel Mod version are you using?

**Comment by GiovanniCardamone** [comment]
The Launcher is: FTBLauncher
The ModPack is: ME^-1 AntiMaterial Energy (v1.0.4)
The Mod is: pearcelmod-1.7.10-1.8.3.jar

**Comment by MiningMark48** [comment]
Try using the latest version of the pack (v0.1.6) or try updating Pearcel Mod to v1.8.7 (or the latest version which might break some things in the pack).

I tested it out by using the latest version of the pack and everything started up fine.

**Comment by GiovanniCardamone** [comment]
where is the list of all version of the pack? i cant find in README.md

**Comment by MiningMark48** [comment]
http://goo.gl/RRJKbF

or you can use the Curse Voice launcher as an easier method for downloading the pack.

**Comment by MiningMark48** [comment]
Let me know if this fixes the issue.

**Comment by GiovanniCardamone** [comment]
ok, so; i cant use curse, because there is no version for linux.
i cant find Pearcel Mod v1.8.7 

i don't know what i have to do; i hope in your's help :)

**Comment by MiningMark48** [comment]
Latest Pearcel Mod: http://goo.gl/Lzpbqe
v1.8.7: http://goo.gl/aeXPLG

**Comment by GiovanniCardamone** [comment]
ok, now i don't have the same error. Seems something not working in fml,forge.

i search for solution. Thanks very much for the help.

**Comment by MiningMark48** [comment]
No problem!
