### ISSUE TITLE
Torcher is missing Mapping

### ISSUE THREAD

**Issue by RKittmann** [MiningMark48/Pearcel-Mod#18]
Placing down torcher crashes the game.Crash report added. 
Version used: 2.0.7

[crash-2016-04-12_15.07.27-server.txt](https://github.com/MiningMark48/Pearcel-Mod/files/215049/crash-2016-04-12_15.07.27-server.txt)

**Comment by MiningMark48** [comment]
I think I know the issue, I will have this fixed ASAP, I won't close this issue until I let you know when a new version is posted.

**Comment by MiningMark48** [comment]
I fixed the issue, I will have a version released soon.

**Comment by parcel31u** [comment]
omg

**Comment by parcel31u** [comment]
I did set the config to place 1 torch every block for 50 blocks

**Comment by MiningMark48** [comment]
The issue wasn't that, at least I don't think it was. It was crashing like the Pearcel Plush. I know why, and it has been fixed, version will be out soon.

**Comment by celestefox** [comment]
Just so you know, I just got the exact same crash with the IVET, so you probably need to fix that too. 
[crash-2016-04-13_15.18.07-server.txt](https://github.com/MiningMark48/Pearcel-Mod/files/217992/crash-2016-04-13_15.18.07-server.txt)

**Comment by MiningMark48** [comment]
I have fixed that as well, it was a common issue between the Torcher, Summoner, Pearcel Plush, and the IVET. Thanks for letting me know anyway.

**Comment by celestefox** [comment]
Okay, just wanted to make sure, as my current world is gonna be unplayable until this is fixed or I worldedit it out :P
(Whoops that sounds pushy, doesn't it. Not meant to sorry, like I said I could probably just Worldedit)

**Comment by MiningMark48** [comment]
I will be releasing a version soon. Sorry for the trouble.

**Comment by MiningMark48** [comment]
A new version has been released, should fix the game crashing issues. [Link](http://minecraft.curseforge.com/projects/pearcel-mod/files/2293988)
