### ISSUE TITLE
[Crash][pearcelmod-1.9.4-2.1.4]Crash while generating new Chunks

### ISSUE THREAD

**Issue by nikkimas** [MiningMark48/Pearcel-Mod#25]
Note: I am on MInecraft 1.10.2. Wanted to say that since its a 1.9.4 mod...

When generating completely new Chunks the server console gets spammed with newly gentated ore positions. And after about 2 minutes, the Server crashes.

Crash-Report: [http://puu.sh/q1How/8fc216240b.txt](http://puu.sh/q1How/8fc216240b.txt) (Sry couldn't use pastebin because the report was over 512Kilobytes...)

**Comment by MiningMark48** [comment]
I ran Pearcel Mod v2.1.4 on Minecraft 1.10.2 fine with no issues. I was not able to replicate the issue. This may be a result of a conflict with another mod. Though, I am not sure. Also, I know of servers running Pearcel Mod v2.1.4 for Minecraft 1.10.2 with no issues.

**Comment by nikkimas** [comment]
ok, so the crash-report isn't telling you anything? Any ideas which mod could have caused that?

**Comment by MiningMark48** [comment]
If it is another mod causing the issues, it might be one of the core mods.

**Comment by nikkimas** [comment]
ok, Seems like it was the mod "TickrateChanger". I removed it and it worked. Sry for the misunderstanding :D

**Comment by MiningMark48** [comment]
No problem, glad I could help. Being that it is 1.10.2 and some of the mods are 1.9.4, it may create conflict sometimes.
